apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: signalfx-agent
    labels:
        version: v1.0.0
        app: signalfx-agent
spec:
    selector:
        matchLabels:
            app: signalfx-agent
    template:
        metadata:
            labels:
                app: signalfx-agent
                version: v1.0.0
        spec:
            hostNetwork: true
            containers:
            - name: signalfx-agent
              image: quay.io/signalfx/signalfx-agent:1.0.0
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /mnt/templates
                  name: templates
                - mountPath: /mnt/integrations
                  name: integrations
                - mountPath: /mnt/config
                  name: config
                - mountPath: /hostfs
                  name: hostfs
                  readOnly: true
                - mountPath: /mnt/proc
                  name: proc
                  readOnly: true
                - mountPath: /var/run/docker.sock
                  name: docker
                  readOnly: true
                - mountPath: /mnt/etc
                  name: etc
                  readOnly: true
              env:
              - name: SFX_ACCESS_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: signalfx
                        key: access-token
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: SFX_MERGE_CONFIG
                value: /etc/signalfx/kubernetes-defaults.yaml
              - name: SFX_USER_CONFIG
                value: /mnt/config/user.yml
            volumes:
              - name: templates
                configMap:
                  name: signalfx-templates
              - name: integrations
                configMap:
                  name: signalfx-integrations
              - name: config
                configMap:
                  name: signalfx-agent
              - hostPath:
                  path: /
                name: hostfs
              - hostPath:
                  path: /proc
                name: proc
              - hostPath:
                  path: /var/run/docker.sock
                name: docker
              - hostPath:
                  path: /etc
                name: etc